#version 450
layout(local_size_x = 256) in;

struct dustBody
{
    vec4 position;
    vec4 velocity;
    vec4 acceleration;
    float radius;
    float mass;
    float _pad0;
    float _pad1;
};

layout(std430, binding = 1) buffer DustSim {
    dustBody particles[];
};

uniform float u_DeltaTime;
uniform uint  u_ParticleCount;

void main()
{
    uint id = gl_GlobalInvocationID.x;
    if (id >= u_ParticleCount) return;

    dustBody p = particles[id];
    if (p.mass <= 0.0) return;

    p.velocity.xyz += p.acceleration.xyz * (0.5 * u_DeltaTime);
    particles[id] = p;
}
