#version 450
layout(local_size_x = 256) in;

struct DustBody {
    vec4 position;
    vec4 velocity;
    float radius;
    float mass;
    float _pad0;
    float _pad1;
};

layout(std430, binding = 0) buffer SimBuffer {
    DustBody sim[];
};

layout(std430, binding = 1) buffer RenderBuffer {
    vec4 renderPos[];
};

void main()
{
    uint id = gl_GlobalInvocationID.x;
    if (id >= sim.length()) return;

    renderPos[id] = sim[id].position;
}
